# Generated by Django 3.1.5 on 2021-01-06 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
            options={
                'verbose_name': 'Игроки',
                'verbose_name_plural': 'Игрок',
                'ordering': ['surname', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тип команды')),
            ],
            options={
                'verbose_name': 'Тип команды',
                'verbose_name_plural': 'Тип команд',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='photos/%Y/%m/%d/', verbose_name='Логотип')),
                ('players', models.ManyToManyField(to='teams.Player', verbose_name='Игроки')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.type', verbose_name='Тип команды')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['name'],
            },
        ),
    ]
