# Generated by Django 3.1.5 on 2021-01-05 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('surname', models.CharField(max_length=64, verbose_name='Фамилия')),
                ('number', models.IntegerField(verbose_name='Номер')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Тип команды')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('logo', models.ImageField(upload_to='', verbose_name='Логотип')),
                ('players', models.ManyToManyField(to='teams.Player', verbose_name='Игроки')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.type', verbose_name='Тип команды')),
            ],
        ),
    ]
